# Generated by Django 5.1.7 on 2025-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Waiting', max_length=20, verbose_name='Status'),
        ),
    ]
