# Generated by Django 5.1.7 on 2025-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_tasks', '0004_alter_task_options_remove_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Shopping', 'Shopping'), ('Fitness', 'Fitness'), ('Health', 'Health'), ('Finance', 'Finance'), ('Study', 'Study'), ('Chores', 'Chores'), ('Travel', 'Travel'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
